# Generated by Django 4.0.2 on 2022-02-15 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='게시일')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
