# Generated by Django 4.0.2 on 2022-02-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_post_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mainphoto',
        ),
    ]
