# Generated by Django 4.0.2 on 2022-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_post_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(default='', max_length=10),
        ),
    ]
