# Generated by Django 4.0.2 on 2022-02-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_post_contents_alter_post_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.post')),
            ],
        ),
    ]
