# Generated by Django 4.0.2 on 2022-02-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_rename_posted_answer_postname'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
