# Generated by Django 4.0.2 on 2022-02-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankapp', '0002_chodangdong_food_chodangdong_rest_gyodong_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('addr', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
