# Generated by Django 4.0.2 on 2022-02-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankapp', '0003_testdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestData',
        ),
    ]
