# Generated by Django 4.0.2 on 2022-02-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestData',
            new_name='sample',
        ),
    ]
