# Generated by Django 4.0.2 on 2022-02-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_testdata_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='addr',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='score',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='title',
            new_name='sc',
        ),
    ]
