# Generated by Django 4.0.2 on 2022-02-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_addr_sample_a_rename_score_sample_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='seoguipo_rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('addr', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
