# Generated by Django 4.0.2 on 2022-02-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_seoguipo_rest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seoguipo_rest',
            new_name='seoguiporest',
        ),
    ]
